### ISSUE TITLE
如何插入照片？

### ISSUE THREAD

**Issue by liujqian** [ZheyuYe/resume-chinese#3]
resume-photo.tex这个文件好像并没有包含照片。请问怎么做出resume-photo.pdf那种效果呢？多谢。

**Comment by zheyuye** [comment]
感谢指出这个问题. 问题来源于`resume-photo.tex`中有关学校logo以及个人照片的相关代码在https://github.com/zheyuye/resume-chinese/commit/13f2a7f632f9ac16eff999efc38ad65a680c90b9 中没有及时更新.

现以在#4 中得到修复,  overleaf版本也会及时更新.
